AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Aster: CFN Template to create am IAM Role for Lambda Function

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Aster
  Modification History:
    - 1.0.0  - May 09, 2023   -- Initial Version 
    
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyIdRegion1
      - KmsMasterKeyIdRegion2
      - KmsMasterKeyIdRegion3
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function:"
      Parameters:
      - LambdaFunctionBaseName
      - LambdaExecutionRoleName
      - LambdaExecutionPolicyName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBTableName
      - DynamoDBGlobalTableRegion2
      - DynamoDBGlobalTableRegion3
    #################################### SQS Queue #################################################
    - Label: 
        default: "SQS Queue:"
      Parameters: 
        - SQSQueueBaseName
    #################################### Kinesis Data Stream #######################################
    - Label: 
        default: "Kinesis Data Stream Configuration:"
      Parameters: 
      - KinesisDataStreamName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## KMS Key ###################################################
      KmsMasterKeyIdRegion1:
        default: KMS Key Id in Region-1.
      KmsMasterKeyIdRegion2:
        default: KMS Key Id in Region-2.
      KmsMasterKeyIdRegion3:
        default: KMS Key Id in Region-3.
      ################################## Lambda Function ###########################################
      LambdaFunctionBaseName: 
        default: "Lammba Function Base Name."
      LambdaExecutionRoleName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyName:
        default: "Lambda Function Execution Policy Name."
      ################################## DynamoDB Table ############################################
      DynamoDBTableName: 
        default: DynamoDB Table Name.
      DynamoDBGlobalTableRegion2: 
        default: DynamoDB Global Table Second Region.
      DynamoDBGlobalTableRegion3: 
        default: DynamoDB Global Table Second Region.
      ################################## SQS Queue #################################################
      SQSQueueBaseName:
        default: "SQS Queue."
      ################################## Kinesis Data Stream #######################################
      KinesisDataStreamName:
        default: Kinesis Data Stream Name.
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: disa
    Description: "The Project Name."
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS Key ###################################################
  KmsMasterKeyIdRegion1: 
    Type: String
    Description: KMS Key Id In Region-1.
    Default: e4c733c5-9fbe-4a90-bda1-6f0362bc9b89
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash.
  KmsMasterKeyIdRegion2: 
    Type: String
    Description: KMS Key Id In Region-2.
    Default: dfc9fe4a-7021-4eb8-a8e9-520a2f91f4f2
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash.
  KmsMasterKeyIdRegion3: 
    Type: String
    Description: KMS Key Id In Region-3.
    Default: 2e99fc66-0257-4f12-841e-38dcddb71a84
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash.
  ##################################### Lambda Function ###########################################
  LambdaFunctionBaseName:
    Default: some-lambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaExecutionRoleName:
    Default: lambda-function-role-name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionPolicyName:
    Default: lambda-function-policy-name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  ###################################### DynamoDB Table ############################################
  DynamoDBTableName:
    Default: aster-customer-order
    Description: The Name Of The DynamoDB Table.
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: DynamoDB table name must be between 10 and 40 characters and must contain only lowercase letters, numbers and dash(-) and must start with a letter.
  DynamoDBGlobalTableRegion2:
    Type: String
    Description: The Second Region Where DynamoDB Global Table Will Be Created.
    Default: us-east-2
    AllowedValues:
      - us-east-2
  DynamoDBGlobalTableRegion3:
    Type: String
    Description: The Third Region Where DynamoDB Global Table Will Be Created.
    Default: us-west-2
    AllowedValues:
      - us-west-2
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Default: "some-sqs-queue"
    Description: "The Base Name Of The Sqs Queue (Dead Letter Quque). The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ###################################### Kinesis Data Stream #######################################
  KinesisDataStreamName:
    Default: aster-kinesis-datastream
    Description: The name of the Kinesis Datastream.
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: Must be between 10 and 40 characters long and begin with a letter and can contain number or hyphen (-).
Resources:
  ###################################### Lambda Execution Role #####################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref LambdaExecutionPolicyName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionBaseName}-${Environment}-${AWS::Region}*'
            - Sid: AllowKinesisDataStream
              Effect: Allow
              Action: 
                - kinesis:ListStreams
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream
                - kinesis:ListShards
              Resource: 
                - !Sub 'arn:${AWS::Partition}:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${KinesisDataStreamName}-${Environment}-${AWS::Region}'
            - Sid: AllowSQSSendMessage
              Effect: Allow
              Action: 
                - sqs:SendMessage
              Resource: 
                - !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${SQSQueueBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowKMSDecryption
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource:
                - !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyIdRegion1}'
                - !Sub 'arn:${AWS::Partition}:kms:${DynamoDBGlobalTableRegion2}:${AWS::AccountId}:key/${KmsMasterKeyIdRegion2}'
                - !Sub 'arn:${AWS::Partition}:kms:${DynamoDBGlobalTableRegion3}:${AWS::AccountId}:key/${KmsMasterKeyIdRegion3}'
            - Sid: AllowDynamoDBWrite
              Effect: Allow
              Action: 
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: 
                - !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}-${Environment}'
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
